### ISSUE TITLE
snippet or pagemethod for header lang helper

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-honehome#1]
i found using snippets a good solution. you could create a snippet wrapping the if-else clause. 

`snippet(‘plugin-honehome’, [‘default’=>’en’]);`

or supply a pagemethod

`$page->honehomeLang(‘en’)`

**Comment by omz13** [comment]
Yes, this is what I should do. I was rushing to get this out in its current form so everybody could have something to work with in case I didn’t have time to get things fully finished for K3.0. Will see what I can do in the next few days.
