### ISSUE TITLE
Parsed "de-DE.UTF8" insted of expected "de"

### ISSUE THREAD

**Issue by johannschopplich** [omz13/kirby3-honehome#2]
Great plugin. Although I ran into the following issue — `lang="de-DE.UTF8"` is the output of:
```php
lang="<?= e($kirby->multilang(), \omz13\k3honehome\localeToLangCode($kirby->language()->locale()), 'de') ?>"
```
<br>

Default language inside `site/languages/de.php`:
```php
<?php
return [
  'code' => 'de',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'de_DE.utf8',
  'name' => 'Deutsch',
  'url' => '/',
]
```

Probably another edge case. 😜

****

I want to mention that — as always — your readme text's are the best out there of any plugins. Thanks and keep it up!

**Comment by omz13** [comment]
Another edge case... sigh... once I have finished playing in the snow outside (Die weiße Scheiße ist hier), and then after several cups of severely strong coffee, I will add some suitably devious code to cope with this. Many thanks for spotting and reporting.

**Comment by johannschopplich** [comment]
Seems only for me
the snow returns `false`
so can't wait to see
that sow lady calls.

An edge case it is
getting fixed very soon
in spite of the bliss
my guess is till moon?

Thx for the fast support.
