### ISSUE TITLE
Incompatible with Kirby 3.1.3

### ISSUE THREAD

**Issue by johannschopplich** [omz13/kirby3-honehome#3]
Since locales can be set as array again (as in v2), your plugin doesn't work anymore:

```
Argument 1 passed to omz13\k3honehome\localeToLangCode() must be of the type string, array given, called in /var/www/virtual/user/example.com/site/plugins/kirby3-honehome/src/config.php on line 30
```

**Comment by omz13** [comment]
@jschopplich Thanks for spotting this. I have a patch, but before pushing, could you send me your `languages/*.php` files so I can test here with your configuration.

**Comment by omz13** [comment]
@jschopplich The root cause is a downstream issue with the 3.1.3 release; there was a breaking change that was put into a patch instead or minor release... I can patch this (and my other plugins) as a workaround.

**Comment by johannschopplich** [comment]
@omz13 Thanks for looking into it. Actually I didn't change anything from my language setup since 3.1.2. Here they are:

`en.php`
```php
return [
  'code' => 'en',
  'default' => false,
  'direction' => 'ltr',
  'locale' => 'en_US.utf8',
  'name' => 'English',
  'url' => 'en'
];
```

`de.php`
```php
return [
  'code' => 'de',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'de_DE.utf8',
  'name' => 'Deutsch',
  'url' => '/'
];
```
